on: [push, pull_request]
name: Continuous integration
jobs:
  test:
    name: run tests and linters
    uses: kubewarden/github-actions/.github/workflows/reusable-test-policy-rust.yml@7195340a122321bf547fda2ffc07eed6f6ae43f6 # v4.5.1

  check-metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: check-policy-metadata
        shell: bash
        run: |
          make check-policy-metadata
